/**
 * Text export.
 *
 * Markdown, because it pastes readably into a notes app, a GitHub issue or a
 * message to whoever is reviewing your resume. Generated locally; nothing is
 * sent anywhere.
 */

import type { CheckState, JobMatch, Report } from '@core/types';

const STATE_MARK: Record<CheckState, string> = {
  pass: '[x]',
  warn: '[!]',
  fail: '[ ]',
  info: '[-]',
};

const SOURCE_LABELS: Record<Report['source'], string> = {
  pdf: 'PDF',
  docx: 'Word document',
  text: 'pasted text',
};

export function reportToMarkdown(report: Report, match: JobMatch | null): string {
  const lines: string[] = [];

  lines.push('# HireReady resume report');
  lines.push('');
  lines.push(`**Score:** ${report.score}/100 - ${report.band.label}`);
  lines.push('');
  lines.push(report.band.message);
  lines.push('');
  lines.push(
    `Source: ${report.fileName ?? SOURCE_LABELS[report.source]} · ` +
      `${report.facts.wordCount} words · ${report.facts.bulletCount} bullets · ` +
      `${report.facts.sectionCount} sections`,
  );
  lines.push(`Generated: ${new Date(report.generatedAt).toLocaleString()}`);
  lines.push('');

  lines.push('## Scores by area');
  lines.push('');
  for (const category of report.categories) {
    lines.push(`- **${category.name}** - ${category.pct}% (${category.score}/${category.weight})`);
  }
  lines.push('');

  lines.push('## Fix these first');
  lines.push('');
  if (report.actions.length === 0) {
    lines.push('Every check passed. Nothing is outstanding.');
  } else {
    report.actions.forEach((check, index) => {
      lines.push(`${index + 1}. **${check.label}** - ${check.summary}`);
      if (check.fix) lines.push(`   ${check.fix}`);
      lines.push('');
    });
  }
  lines.push('');

  lines.push('## Every check');
  lines.push('');
  for (const category of report.categories) {
    lines.push(`### ${category.name} (${category.score}/${category.weight})`);
    lines.push('');
    for (const check of category.checks) {
      lines.push(`- ${STATE_MARK[check.state]} **${check.label}** - ${check.summary}`);
      if (check.fix) lines.push(`      Fix: ${check.fix}`);
      if (check.evidence?.length) lines.push(`      Found: ${check.evidence.join(', ')}`);
    }
    lines.push('');
  }

  if (match) {
    lines.push('## Against the job posting');
    lines.push('');
    lines.push(
      `Covers ${match.coverage}% of the posting's key terms and ` +
        `${match.skillCoverage}% of its named tools. Not part of the score.`,
    );
    lines.push('');
    if (match.matched.length) {
      lines.push(`**Already present:** ${match.matched.map((t) => t.term).join(', ')}`);
      lines.push('');
    }
    if (match.missing.length) {
      lines.push(`**Missing:** ${match.missing.map((t) => t.term).join(', ')}`);
      lines.push('');
      lines.push('Add only the ones that are genuinely true of you.');
      lines.push('');
    }
  }

  lines.push('---');
  lines.push('');
  lines.push(
    'Generated by HireReady. Screening systems differ between companies, and many ' +
      'smaller firms read every resume by hand. This is a checklist of what commonly ' +
      'goes wrong, not a number any employer sees.',
  );

  return lines.join('\n');
}

/** A filesystem-safe name for the downloaded report. */
export function reportFileName(report: Report): string {
  const base = report.fileName?.replace(/\.[^.]+$/, '') ?? 'resume';
  const slug =
    base
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '')
      .slice(0, 48) || 'resume';
  const stamp = new Date(report.generatedAt).toISOString().slice(0, 10);
  return `hireready-${slug}-${stamp}.md`;
}

/** Triggers a download without a server round trip. */
export function downloadText(fileName: string, contents: string): void {
  const blob = new Blob([contents], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = fileName;
  document.body.append(link);
  link.click();
  link.remove();
  // Give the browser a moment to start the download before revoking.
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    // Clipboard API needs a secure context and permission. Fall back to a
    // hidden textarea, which still works on older Safari and over plain HTTP.
    try {
      const helper = document.createElement('textarea');
      helper.value = text;
      helper.setAttribute('readonly', '');
      helper.style.position = 'fixed';
      helper.style.opacity = '0';
      document.body.append(helper);
      helper.select();
      const ok = document.execCommand('copy');
      helper.remove();
      return ok;
    } catch {
      return false;
    }
  }
}
