/**
 * Downloads the webfonts into public/fonts so the site serves them itself.
 *
 * HireReady promises that nothing about a resume leaves the browser. Loading
 * fonts from a third-party CDN would still hand that party every visitor's IP
 * and user agent, so the fonts are vendored instead.
 *
 * Run this once, or again when the font list changes:
 *   node scripts/fetch-fonts.mjs
 *
 * The output is committed, so a normal build needs no network access.
 */

import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath, URL as NodeURL } from 'node:url';

/**
 * Kept deliberately short. Each extra weight is another 20-75kB, and the
 * browser can synthesise the in-between weights well enough here.
 */
const GOOGLE_CSS = new NodeURL(
  'https://fonts.googleapis.com/css2' +
    '?family=Newsreader:ital,opsz,wght@0,6..72,500;0,6..72,600;1,6..72,500' +
    '&family=IBM+Plex+Sans:wght@400;500;600' +
    '&family=IBM+Plex+Mono:wght@400;500' +
    '&display=swap',
);

/** Only these subsets are kept. The rest would triple the payload unused. */
const WANTED_SUBSETS = new Set(['latin', 'latin-ext']);

/** Google only serves woff2 to modern UA strings. */
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const outDir = fileURLToPath(new NodeURL('../public/fonts/', import.meta.url));

function slugify(value) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

async function main() {
  await mkdir(outDir, { recursive: true });

  const response = await fetch(GOOGLE_CSS, { headers: { 'User-Agent': UA } });
  if (!response.ok) throw new Error(`Font CSS request failed: ${response.status}`);
  const css = await response.text();

  // Each @font-face is preceded by a /* subset */ comment.
  const blocks = [...css.matchAll(/\/\*\s*([a-z0-9-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/gi)];
  if (blocks.length === 0) throw new Error('No @font-face blocks found in the response.');

  const out = [
    '/*',
    ' * Self-hosted webfonts. Generated by scripts/fetch-fonts.mjs — do not edit.',
    ' * Newsreader, IBM Plex Sans and IBM Plex Mono are all licensed under',
    ' * the SIL Open Font License 1.1. See public/fonts/OFL.txt.',
    ' */',
    '',
  ];

  let downloaded = 0;

  for (const [, subset, block] of blocks) {
    if (!WANTED_SUBSETS.has(subset)) continue;

    const family = /font-family:\s*'([^']+)'/.exec(block)?.[1];
    const weight = /font-weight:\s*([^;]+);/.exec(block)?.[1]?.trim() ?? '400';
    const style = /font-style:\s*([^;]+);/.exec(block)?.[1]?.trim() ?? 'normal';
    const range = /unicode-range:\s*([^;]+);/.exec(block)?.[1]?.trim();
    const url = /url\((https:\/\/[^)]+\.woff2)\)/.exec(block)?.[1];
    if (!family || !url) continue;

    const name = [slugify(family), slugify(weight), style === 'italic' ? 'italic' : null, subset]
      .filter(Boolean)
      .join('-');
    const file = `${name}.woff2`;

    const fontResponse = await fetch(url, { headers: { 'User-Agent': UA } });
    if (!fontResponse.ok) throw new Error(`Failed to download ${url}: ${fontResponse.status}`);
    const bytes = Buffer.from(await fontResponse.arrayBuffer());
    await writeFile(new NodeURL(file, `file://${outDir}`), bytes);
    downloaded += 1;
    console.log(`  ${file}  ${(bytes.length / 1024).toFixed(1)}kB`);

    out.push(
      '@font-face {',
      `  font-family: '${family}';`,
      `  font-style: ${style};`,
      `  font-weight: ${weight};`,
      '  font-display: swap;',
      `  src: url('./${file}') format('woff2');`,
      ...(range ? [`  unicode-range: ${range};`] : []),
      '}',
      '',
    );
  }

  await writeFile(new NodeURL('fonts.css', `file://${outDir}`), out.join('\n'), 'utf8');
  console.log(`\nWrote public/fonts/fonts.css with ${downloaded} font files.`);
}

main().catch((error) => {
  console.error(`\nFont download failed: ${error.message}`);
  process.exit(1);
});
